### ISSUE TITLE
Push version 1.7.2 to NPM

### ISSUE THREAD

**Issue by gabrielgrant** [x3dom/dist#1]
The [current version of X3DOM on NPM](https://www.npmjs.com/package/x3dom) still seems to be 1.7.1 (from a year ago). Any chance of getting the latest version pushed there? Thanks!

**Comment by fibo** [comment]
Sorry for the delay, anyway you should find v1.7.2 on npm (published 2 years ago).
I double checked first line of x3dom.js says

```
/** X3DOM Runtime, http://www.x3dom.org/ 1.7.2 - 61a235203deb34329fe615cbbf21314db6ebf49f - Mon Dec 19 19:17:05 2016 +0100 */
```
